version: 2.1

orbs:
  node: circleci/node@5.0.3

jobs:
  test:
    machine:
      image: 'ubuntu-2204:current'
    steps:
      - checkout
      - node/install:
          node-version: '16.14'
      - run:
          name: Install PNPM
          command: |
            curl -fsSL https://get.pnpm.io/install.sh | env PNPM_VERSION=8.1.0 sh -
      - restore_cache:
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Setup dependencies
          command: |
            sudo NEEDRESTART_MODE=a apt update -y
            sudo NEEDRESTART_MODE=a apt install libudev-dev -y
            npm install --global node-gyp
            pnpm install --frozen-lockfile --store-dir ~/.cache/pnpm
      - run:
          name: Lint
          command: pnpm lint
      - run:
          name: Test APIs
          command: pnpm test:coverage
      - run:
          name: Test Integration
          command: pnpm test:integration
          environment:
            ELECTRON_ENABLE_LOGGING: true
            VITE_CI: true
      - save_cache:
          paths:
            - '~/.cache/pnpm'
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}

workflows:
  test:
    jobs:
      - test
