version: 2.1

orbs:
  node: circleci/node@5.0.3

jobs:
  test:
    machine:
      image: 'ubuntu-2204:current'
    steps:
      - checkout
      - node/install:
          node-version: '22.14'
          install-yarn: true
      - restore_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Setup dependencies
          command: |
            yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test APIs
          command: yarn test:coverage
      - run:
          name: Test Integration
          command: yarn test:integration
          environment:
            ELECTRON_ENABLE_LOGGING: true
            VITE_CI: true
      - save_cache:
          paths:
            - '~/.cache/yarn'
          key: yarn-packages-{{ checksum "yarn.lock" }}

workflows:
  test:
    jobs:
      - test
