version: 2.1

orbs:
  node: circleci/node@5.0.3

jobs:
  test:
    machine:
      image: 'ubuntu-2204:current'
    steps:
      - checkout
      - node/install:
          node-version: '20.16'
          install-yarn: true
      - restore_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Setup dependencies
          command: |
            sudo NEEDRESTART_MODE=a apt update -y
            sudo NEEDRESTART_MODE=a apt install libudev-dev -y
            yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test APIs
          command: yarn test:coverage
      - save_cache:
          paths:
            - '~/.cache/yarn'
          key: yarn-packages-{{ checksum "yarn.lock" }}
  enforce-version-bump:
    machine:
      image: 'ubuntu-2204:current'
    steps:
      - checkout
      - run:
          name: Install jq
          command: |
            sudo apt-get update -y
            sudo apt-get install -y jq
      - run:
          name: Fetch main
          command: |
            git fetch --no-tags --depth=1 origin main
      - run:
          name: Enforce version bump
          command: |
            set -euo pipefail

            BASE_BRANCH="origin/main"

            CURRENT_VERSION="$(jq -r '.version' package.json)"
            BASE_VERSION="$(git show ${BASE_BRANCH}:package.json 2>/dev/null | jq -r '.version')"

            echo "Base version:    ${BASE_VERSION}"
            echo "Current version: ${CURRENT_VERSION}"

            if [ "${BASE_VERSION}" = "${CURRENT_VERSION}" ]; then
              echo "ERROR: Changes detected but package.json version was not updated. Please bump the version."
              exit 1
            fi

            echo "Version changed; passing."

workflows:
  test:
    jobs:
      - test
      - enforce-version-bump:
          filters:
            branches:
              ignore:
                - main
